# Generated by Django 6.0.1 on 2026-04-16 11:32

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simple_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='section_images/')),
            ],
            options={
                'verbose_name': 'Image Section',
                'verbose_name_plural': 'Image Sections',
            },
            bases=('simple_page.section',),
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('simple_page.page',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TextSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Text Section',
                'verbose_name_plural': 'Text Sections',
            },
            bases=('simple_page.section',),
        ),
    ]
