# Generated by Django 6.0.1 on 2026-04-15 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
        ('simple_page', '0002_alter_pageregion_index_alter_pagesection_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftSidebar',
            fields=[
                ('region_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.region')),
            ],
            bases=('simple_page.region',),
        ),
        migrations.CreateModel(
            name='MainRegion',
            fields=[
                ('region_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.region')),
            ],
            bases=('simple_page.region',),
        ),
    ]
