# Generated by Django 6.0.1 on 2026-04-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_leftsidebar_mainregion'),
        ('simple_page', '0002_alter_pageregion_index_alter_pagesection_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('simple_page.page',),
        ),
    ]
