# Generated by Django 6.0.1 on 2026-04-11 12:12

import django.db.models.deletion
import mptt.fields
import simple_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(simple_page.models.HTMLMixin, simple_page.models.ShowChildClassNameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(simple_page.models.HTMLMixin, simple_page.models.ShowChildClassNameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='simple_page.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, simple_page.models.ShowChildClassNameMixin, simple_page.models.HTMLMixin),
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(blank=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_page.page')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_page.section')),
            ],
            options={
                'ordering': ['page__id', 'index'],
                'unique_together': {('page', 'index'), ('page', 'section')},
            },
            bases=(simple_page.models.OrderedRelationMixin, models.Model),
        ),
        migrations.AddField(
            model_name='page',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='pages', through='simple_page.PageSection', to='simple_page.section'),
        ),
        migrations.CreateModel(
            name='PageRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(blank=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_page.page')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_page.region')),
            ],
            options={
                'ordering': ['page__id', 'index'],
                'unique_together': {('page', 'index'), ('page', 'region')},
            },
            bases=(simple_page.models.OrderedRelationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RegionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(blank=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_page.region')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_page.section')),
            ],
            options={
                'ordering': ['region__id', 'index'],
                'unique_together': {('region', 'index'), ('region', 'section')},
            },
            bases=(simple_page.models.OrderedRelationMixin, models.Model),
        ),
    ]
