# Generated by Django 6.0.1 on 2026-06-05 17:07

import reorder_items_widget.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagesection',
            options={'ordering': ['page', 'region', 'index']},
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='index',
            field=reorder_items_widget.models.ReorderItemsField(blank=True, verbose_name='Index'),
        ),
    ]
