# Generated by Django 6.0.1 on 2026-04-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageregion',
            name='index',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='index',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='regionsection',
            name='index',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
