# Generated by Django 6.0.1 on 2026-04-09 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['parent__id', 'order']},
        ),
        migrations.AlterModelOptions(
            name='pagesection',
            options={'ordering': ['page__id', 'order']},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('parent', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='pagesection',
            unique_together={('page', 'order'), ('page', 'section')},
        ),
    ]
