# Generated by Django 6.0.1 on 2026-04-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='region',
            field=models.CharField(default='main', max_length=255, verbose_name='Region'),
        ),
    ]
