# Generated by Django 6.0.1 on 2026-04-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_page', '0002_pagesection_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='region',
            field=models.CharField(max_length=255, verbose_name='Region'),
        ),
    ]
