# Generated by Django 6.0.1 on 2026-04-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_page', '0002_alter_page_options_alter_pagesection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='order',
            field=models.IntegerField(blank=True),
        ),
    ]
