# Generated by Django 6.0.1 on 2026-04-22 08:19

import django.db.models.deletion
import simple_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('simple_page', '0003_alter_pagesection_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
