# Generated by Django 6.0.1 on 2026-04-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_page', '0003_alter_pagesection_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='page',
            name='ordering',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.IntegerField(),
        ),
    ]
