# Generated by Django 6.0.1 on 2026-04-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_page', '0004_alter_page_options_page_ordering_alter_page_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='ordering',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
