# Generated by Django 6.0.1 on 2026-04-27 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simple_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.page')),
                ('special_info', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('simple_page.page',),
        ),
        migrations.CreateModel(
            name='TextSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('text', models.TextField(blank=True)),
            ],
            bases=('simple_page.section',),
        ),
        migrations.CreateModel(
            name='TextWithTitleSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
            ],
            bases=('simple_page.section',),
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('simple_page.page',),
        ),
    ]
