# Generated by Django 6.0.1 on 2026-05-19 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_page', '0001_initial'),
        ('test_project', '0002_textsection_title_delete_textwithtitlesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageWithHeader',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.page')),
                ('header_info', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('simple_page.page',),
        ),
        migrations.DeleteModel(
            name='ExtraPage',
        ),
    ]
